name: "test Action"
description: "hell no"
author: "@JuryA"

input:
    MY_NAME:
        description: "who to eat"
        required: true
        default: "Mango"
runs:
    using: "docker"
    image: "Dockerfile"

branding:
    icon: "mic"
    color: "purple"