name: A workflow
on: push
jobs:
    build:
        name: hello job here
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v1
             - uses: ./ 
               env:
                  URL: ${{ secrets.URL }}
                  OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
                  USER: ${{ secrets.USER }}
                  EMAIL: ${{ secrets.USER }}
