name: Scrapping Workflow
on: push
jobs:
    build:
        name: Import Varibles and Deploying
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v1
             - uses: ./ 
               env:
                  URL: ${{ secrets.URL }}
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  USER: ${{ secrets.USER }}
